### ISSUE TITLE
[提案] Webhook を用いたメッセージの送信

### ISSUE THREAD

**Issue by tsuyopon123** [nekoy3/RoomManageBot#4]
こんにちは。
機能の提案です。

複数チャンネルでのメッセージの共有機能のメッセージ送信について、 Discord の Webhook を利用してみてはいかがでしょうか。
Discord の Webhook は、メッセージごとにユーザ名やユーザのアイコン画像を指定することが可能です。
https://discord.com/developers/docs/resources/webhook
そのため、 Discord Bot からのメッセージと比べて誰が送信したメッセージか分かりやすくなるのではないでしょうか。

Webhook を用いたメッセージ送信は、 Slack と Discord など異なるプラットフォーム同士でメッセージの共有を行う Bot などの実装によく見られます。
また多くの Discord API ライブラリにて Webhook がサポートされています。
検討してみてください。

**Comment by nekoy3** [comment]
提案ありがとうございます！
Webhookについてはあまり詳しく触れたことがなく、そういった機能があることも把握していませんでした。
色々調べて、実装出来るようにやってみます。

**Comment by tsuyopon123** [comment]
メッセージの共有機能の実装お疲れさまですー！
本issueは閉じますー．

@waveringdonut くんからちょこちょここのbotについて聞いてます．
次はKotlinを使って開発するんですね．頑張ってください💪💪
ユーザからのメッセージ取得をスラッシュコマンドからしかできないみたいなことを聞いたので，自分でもpy-cordを使って実装してみました．
https://github.com/tsuyopon123/discord-channel-sync
(昔と比べて権限周りが複雑になってて驚きました…)
もし良ければ参考にしてみてくださいー
バグとか不明点とかあればぜひ聞いてください．
